### ISSUE TITLE
Make it play nice with gradle-node-plugin

### ISSUE THREAD

**Issue by dsvensson** [sothmann/typescript-gradle-plugin#20]
It would be nice if this typescript plugin cooperated with the node plugin for gradle which installs node and npm. That is.. the ability to extract executable path for node from gradle-node-plugin, and perhaps also install a requested typescript version via the npm it installs, both npm and node are installed locally under ~/.gradle. This would simplify the interaction with a typescript + gradle based project.

https://github.com/srs/gradle-node-plugin

**Comment by sothmann** [comment]
Yes I'm also thinking about this for quite some time. I will see what I can do regarding the node interaction.

**Comment by dsvensson** [comment]
Currently it's pretty effortless to glue these two projects together though:

    def getNodeVariant() {
        def ext = NodeExtension.get(project)
        return new VariantBuilder(ext).build()
    }

    compileTypeScript {
        sourcemap = true
        compilerExecutable "${getNodeVariant().nodeExec} node_modules/typescript/lib/tsc.js"

        dependsOn "npmSetup"
    }

**Comment by sothmann** [comment]
Thank you very much for pointing this out! I will update the Readme with
your solution for the node Integration!

Daniel Svensson <notifications@github.com> schrieb am Fr., 1. Jan. 2016
11:43:

**Comment by dsvensson** [comment]
I've also filed a ticket about generating package.json from within build.gradle, similar to how the bower plugin works so you don't have to have the typescript dependency and its version in an external file, hopefully someone picks it up, https://github.com/srs/gradle-node-plugin/issues/93 ... worth keeping an eye on. I personally don't have the time yet to work on that right now so external file will have to do.
