### ISSUE TITLE
Make the plugin available on plugins.gradle.org

### ISSUE THREAD

**Issue by dsvensson** [sothmann/typescript-gradle-plugin#21]
By having the plugin there, a more concise import can be made. 

As an example, here's the node plugin:

Old style:

    buildscript {
        repositories {
            maven {
                url "https://plugins.gradle.org/m2/"
            }
        }
    
        dependencies {
            classpath "com.moowork.gradle:gradle-node-plugin:0.11"
        }
    }

    apply plugin: 'com.moowork.node'

New style:

    plugins {
        id "com.moowork.node" version "0.11"
    }

More details at https://plugins.gradle.org/docs/submit

**Comment by sothmann** [comment]
Starting with version 1.7.1, the plugin is available in the official Gradle plugin repository.
See https://plugins.gradle.org/plugin/de.richsource.gradle.plugins.typescript
