### ISSUE TITLE
why not webjars?

### ISSUE THREAD

**Issue by dimalinux** [sothmann/typescript-gradle-plugin#25]
I know this isn't an issue, but I'm hoping others that have the same question will find the answer helpful:

I was expecting a Spring Boot + Gradle project to use Webjars for Javascript dependency management.  Why did this example project choose a different route?  Was it just a coin-flip, or is there a reason I don't want to use Webjars in my first Typescript project?

Thanks!

**Comment by sothmann** [comment]
Are you referring to the [JavaTypescriptWebapp](https://github.com/sothmann/typescript-gradle-plugin/tree/master/examples/JavaTypescriptWebapp) example?
That example is intended to show how to use the TypeScript Gradle Plugin in a Gradle build.gradle file - nothing more.
The example doesn't use any JavaScript libraries, so there is no need for WebJars.

Or did I misunderstand your question?

**Comment by dimalinux** [comment]
I'm new to TypeScript.  I was looking for how to get Gradle + Spring Boot to play nice with TypeScript, so I could learn TypeScript in the tools/frameworks I use daily.

Your TypeScript Gradle plugin is the simplest solution I've seen so far, but it has dependencies not handled by Gradle.  The instructions have the user install Node.js and then TypeScript using Node's package manager.

There are webjars for TypeScript from Maven Central:
```
'org.webjars:typescript:1.7.5' 
'org.webjars:typescript-node:1.7.5'
'org.webjars.npm:typescript:1.8.10'
```
If I understand correctly, the TypeScript compiler is written in TypeScript.  The compiled JavaScript to run this compiler is available on Maven Central. Would one of those webjars be sufficient for a TypeScript Gradle plugin that doesn't require Node.js to be installed?  On the TypeScript website, they appear to be compiling TypeScript right in the client browser, so I thought compilation might be doable in the NashHorn interpreter.

**Comment by sothmann** [comment]
OK, now I understand what you are asking for.

Yes you are right, at the moment the plugin relies on dependencies to be installed manually, but there is a simple workaround. Use the node plugin like this:
```
String nodeExecutable() {
  NodeExtension nodeExt = NodeExtension.get(project)
  return new VariantBuilder(nodeExt).build().nodeExec
}

compileTypeScript {
  compilerExecutable "${nodeExecutable()} node_modules/typescript/lib/tsc.js"
  dependsOn "npmInstall"
}
```

You need to place a `package.json` file next to the `build.gradle` where you declare the typescript compiler version like this:
```{
  "dependencies": {
    "typescript": "1.8.0"
  }
}```

Sorry that I did not update the readme with this solution - I will hopefully update it the next days.

I'd like to bundle the TypeScript compiler with the plugin in the future - but that feature is not implemented yet.

Regarding your original question on using WebJars and Nashorn: Nashorn is way slower than Node, which makes it not a good choice. Compile times matter a lot for larger projects, so I think Nashorn is not a serious option, unfortunately.
