### ISSUE TITLE
The maven repo url in the README returns 404

### ISSUE THREAD

**Issue by cg-soft** [sothmann/typescript-gradle-plugin#9]
https://github.com/sothmann/typescript-gradle-plugin/raw/mavenrepo/ doesn't appear to exist.

**Comment by sothmann** [comment]
Thanks for reporting this issue. Seems that Github does not longer allow that kind of file access.
I am going to upload the plugin to Bintray soon. Be patient.

**Comment by sothmann** [comment]
Please try again with the following URL:
https://dl.bintray.com/sothmann/gradle-plugins

**Comment by sothmann** [comment]
The plugin now has been published in jcenter.
You can use it as follows:
```
buildscript {
    repositories {
       jcenter()
    }
    dependencies {
        classpath 'de.richsource.gradle.plugins:typescript-gradle-plugin:1.1'
    }
}
```
